### ISSUE TITLE
Screenshot for Reverse Proxy contains an error

### ISSUE THREAD

**Issue by neoKushan** [ulyaoth/tutorials#3]
The screenshot for the Reverse Proxy configuration shows the "Inbound rules" to be configured as 

http://127.0.0.1:5601

However this is a mistake and causes URLs to be rewritten as http://http://

Correct configuration is just:

127.0.0.1:5601

**Comment by sbagmeijer** [comment]
Hmm I will have a look at it this weekend I will update the guide to the 2.0 versions.

**Comment by sbagmeijer** [comment]
Thank you very much again for the report I have updated the guide now with all the new version and I also fixed the screenshot for the problem above!

https://www.ulyaoth.net/resources/tutorial-install-logstash-and-kibana-on-a-windows-server.34/

**Comment by neoKushan** [comment]
No problem, thanks for updating it! Your guide was perfect aside from the 2 issues I found and 1 of those was just due to version 2.0.
