### ISSUE TITLE
Images broken on tutorial page

### ISSUE THREAD

**Issue by hadsy** [ulyaoth/tutorials#9]
FYI, I'm getting a 403 error for all images so they don't show for this URL:
https://www.ulyaoth.net/resources/tutorial-install-logstash-and-kibana-on-a-windows-server.34/

Great tutorial!

**Comment by sbagmeijer** [comment]
Thank you for the report @hadsy !

I had to move hosting apparently selinux was not allowing the images to be loaded by the web-server :/ ...

But all fixed now! I appreciate the kind works :+1:
